#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# index.py
# Example usage and main entry point for regex moderation scorer

from scorer import RegexModerationScorer

if __name__ == "__main__":
    scorer = RegexModerationScorer()

    samples = [
        # Original samples
        "I just had a great intercourse last night, it felt really amazing.",
        "I just had a great sex today, haha, can't stop thinking about it.",
        "I just had a great sex today, honestly feels so good.",
        "Serba salah sih, asal gak lebih dari sekadar ngobrol santai aja.",
        "Iya serius, kalo pengen mah sebenernya bisa diatur.",
        "Bisa jadi ada kemungkinan, tapi tergantung kamu juga.",
        "Selain app ini, kamu ada kontak lain?",
        "Hmm, keberatan gak kalo bahas yang agak dewasa dikit?",
        "Boleeeh mas, per jamnya 15 juta ya.",
        "Soalnya dia tau G-spot gua, jadi cepet nyaman.",
        "Dirty, tapi hot jujur aja.",
        "T.e.l.e?",
        "Gmeet aja kali ya, biar lebih enak ngobrolnya.",
        "L.i.n.e?",
        "I just had an amazing adult experience, still feels unreal.",
        "Atau Telegram?",
        "Ada Line?",
        
        # Obfuscation variations - Leet speak
        "s3x dong",
        "s3ks nih",
        "ngent0t yuk",
        "ent0t aja",
        "$ex time",
        "s@x",
        "s*e*x",
        "s e x",
        "s-e-x",
        "s.e.x",
        "s_e_x",
        
        # Obfuscation variations - Platform names
        "T.e.l.e.g.r.a.m",
        "W.A",
        "W.A.H.A.T.S.A.P.P",
        "L.I.N.E",
        "I.G",
        "I.N.S.T.A.G.R.A.M",
        "tele.gram",
        "wa.ts.app",
        "li.ne",
        "t-e-l-e",
        "w-a",
        "l-i-n-e",
        
        # Suggestive/Sexual content variations
        "Dirty, tapi hot",
        "Seksi banget",
        "Hot nih",
        "Mesum dikit",
        "Nakal ya",
        "Kotor sih",
        "Sexy time",
        
        # Rates/Money variations
        "per jam 500rb",
        "perjam 1jt",
        "per malam 2 juta",
        "permalam 15jt",
        "rate 500k",
        "tarif per jam",
        "fee 1 juta",
        
        # Contact requests variations
        "minta nomor dong",
        "boleh wa?",
        "kasih kontak",
        "drop telegram",
        "ada line?",
        "kontak lain dong",
        "kontak luar?",
        "kontak lainnya?",
        
        # Meeting/Modus variations
        "ketemu yuk",
        "meet up aja",
        "jalan-jalan",
        "ngopi bareng",
        "hotel aja",
        "kamar kosan",
        "nginep",
        "apartemen",
        
        # Coercion/Manipulation variations
        "asal kamu mau",
        "kalau kamu mau",
        "tenang aja",
        "gak usah takut",
        "percaya sama aku",
        "rahasia",
        "jangan bilang siapa",
        "bisa diatur",
        "pengen",
        "diatur aja",
        
        # Adult content variations
        "konten dewasa",
        "adult only",
        "18+",
        "konten untuk dewasa",
        
        # Nudity variations
        "bugil",
        "telanjang",
        "nude",
        "naked",
        "kirim nude",
        "send nude",
        "share foto bugil",
        "kirim video telanjang",
        
        # Genitals variations
        "kontol",
        "memek",
        "penis",
        "vagina",
        "pussy",
        "dick",
        "cock",
        "boobs",
        "tetek",
        "payudara",
        "g spot",
        "gspot",
        
        # Explicit acts variations
        "sex",
        "seks",
        "ngentot",
        "entot",
        "masturbasi",
        "ngewe",
        "hentai",
        "porn",
        "bokep",
        "xnxx",
        "xvideos",
        "intercourse",
        
        # Phishing/Scam variations
        "otp nya berapa?",
        "kirim otp",
        "kode verifikasi",
        "verification code",
        "kirim pin",
        "share otp",
        
        # Harassment variations
        "anjing",
        "bangsat",
        "bego",
        "tolol",
        "goblok",
        "brengsek",
        "asu",
        "kampret",
        "gua bunuh",
        "tak bunuh",
        "mati aja",
        "hajar",
        "gebuk",
        "laporin",
        
        # Complex obfuscation combinations
        "s3x dong, kirim nude",
        "pindah wa, per jam 1jt",
        "hotel aja, bisa diatur",
        "ketemu yuk, kontak lain?",
        "dewasa dikit, mesum",
        "T.e.l.e aja, lebih aman",
        "perjamnya 500rb, ketemu",
        
        # Typo variations - intentional misspelling
        "seks dong",
        "s3ks nih",
        "s3x aja",
        "ngentot yuk",
        "ngent0t aja",
        "ngentot dong",
        "kontol",
        "kont0l",
        "k0ntol",
        "kontol dong",
        "memek",
        "m3mek",
        "mem3k",
        "pepek",
        "p3pek",
        "pep3k",
        "entot",
        "ent0t",
        "3ntot",
        "bokep",
        "b0kep",
        "bok3p",
        "bokep dong",
        "porn",
        "p0rn",
        "porn aja",
        "hentai",
        "h3ntai",
        "hent4i",
        
        # Symbol variations - symbols as letter replacements
        "$ex",
        "s$x",
        "$ex time",
        "s@x",
        "s@x dong",
        "@sex",
        "se@",
        "nude",
        "nud3",
        "nud€",
        "nude dong",
        "hot",
        "h0t",
        "h*t",
        "hot nih",
        "dirty",
        "d1rty",
        "d!rty",
        "dirty aja",
        
        # Mixed symbols and typos
        "s3x$",
        "$3x",
        "s@x dong",
        "ngent0t$",
        "kont0l!",
        "m3m3k",
        "p3p3k",
        "b0k3p",
        "h3nt4i",
        
        # Repeated characters (common typo pattern)
        "seksss",
        "sexxxx",
        "ngentott",
        "kontoll",
        "memekk",
        "bokeeep",
        "pornnn",
        "nudeee",
        "hott",
        "dirtyyy",
        
        # Mixed case with typos
        "SeKs",
        "SeX",
        "NgeNt0t",
        "KoNt0l",
        "MeMeK",
        "BoKeP",
        "PoRn",
        "NuDe",
        "HoT",
        "DiRtY",
        
        # Platform names with typos/symbols
        "telegram",
        "t3l3gram",
        "t3l3gr@m",
        "telegramm",
        "telegram dong",
        "whatsapp",
        "w4tsapp",
        "w4ts@pp",
        "whatsappp",
        "wa",
        "w4",
        "w@",
        "wa dong",
        "line",
        "l1ne",
        "l!ne",
        "line dong",
        "instagram",
        "inst4gram",
        "instagramm",
        "ig",
        "1g",
        "!g",
        
        # Rates/money with typos
        "per jam",
        "p3r jam",
        "per j4m",
        "perjam",
        "p3rjam",
        "perjam dong",
        "tarif",
        "t4rif",
        "tariff",
        "rate",
        "r4te",
        "rat3",
        "juta",
        "jut4",
        "jut@",
        "juta dong",
        
        # Contact requests with typos
        "minta nomor",
        "mint4 nomor",
        "minta nom0r",
        "minta nomor dong",
        "kontak",
        "k0ntak",
        "kont4k",
        "kontak dong",
        "kontak lain",
        "kont4k l4in",
        "kontak l4in",
        
        # Meeting/Modus with typos
        "ketemu",
        "ket3mu",
        "ket3m@",
        "ketemu yuk",
        "hotel",
        "h0tel",
        "hot3l",
        "hotel dong",
        "kamar",
        "k4mar",
        "kam4r",
        "kamar dong",
        "nginep",
        "ngin3p",
        "ngin3p dong",
        
        # Coercion/manipulation with typos
        "bisa diatur",
        "bis4 diatur",
        "bisa di4tur",
        "diatur",
        "di4tur",
        "diatur dong",
        "pengen",
        "peng3n",
        "peng3n dong",
        "rahasia",
        "r4hasia",
        "rah4sia",
        
        # Adult content with typos
        "dewasa",
        "dew4sa",
        "dew4s@",
        "dewasa dikit",
        "adult",
        "@dult",
        "4dult",
        "adult only",
        
        # Nudity with typos
        "bugil",
        "bug1l",
        "bug!l",
        "bugil dong",
        "telanjang",
        "tel4njang",
        "telanj4ng",
        "naked",
        "n4ked",
        "nak3d",
        
        # Genitals with typos
        "penis",
        "p3nis",
        "pen!s",
        "vagina",
        "v4gina",
        "vag1na",
        "pussy",
        "puss3",
        "puss!",
        "dick",
        "d1ck",
        "d!ck",
        "cock",
        "c0ck",
        "c0ck",
        "boobs",
        "bo0bs",
        "b00bs",
        "gspot",
        "gsp0t",
        "gsp@t",
        
        # Harassment with typos
        "anjing",
        "@njing",
        "4njing",
        "bangsat",
        "b4ngsat",
        "bangsaat",
        "bego",
        "b3go",
        "beg0",
        "tolol",
        "t0lol",
        "tol0l",
        "goblok",
        "g0blok",
        "gobl0k",
        "asu",
        "@su",
        "4su",
        "kampret",
        "k4mpret",
        "kampreet",
        
        # Complex combinations with typos/symbols
        "s3x dong, kirim nud3",
        "pindah w4, per j4m 1jt",
        "h0tel aja, bis4 di4tur",
        "ket3mu yuk, kont4k l4in?",
        "dew4s4 dikit, m3sum",
        "t3l3gram aja, lebih aman",
        "perj4mnya 500rb, ket3mu",
        "$3x dong, kirim @",
        "ngent0t$ yuk",
        "kont0l! dong",
        "m3m3k nih",
        "b0k3p aja",
        "p0rn dong",
        "h3nt4i nih",
        "nud3 aja",
        "h0t nih",
        "d!rty aja",
        "seksss dong",
        "sexxxx aja",
        "ngentott yuk",
        "kontoll dong",
        "memekk nih",
        "bokeeep aja",
        "pornnn dong",
        "nudeee nih",
        "hott aja",
        "dirtyyy dong",
        
        # Context-aware test cases - harus nyambung konteksnya
        "kirim nude dong",
        "tolong kirim foto nude",
        "bantu kasih video bugil",
        "minta foto telanjang",
        "kasih gambar nude",
        "send pic bugil",
        "mau sex nih",
        "pengen seks",
        "ingin ngentot",
        "minta ml",
        "mau make love",
        "pengen sex bareng",
        "bayar 500rb",
        "transfer 1 juta",
        "kirim uang 2jt",
        "kasih duit 500rb",
        "bayar per jam",
        "transfer dulu",
        "kirim rupiah",
        "kasih money dong",
        
        # Context combinations
        "minta foto nude, bayar 500rb",
        "kirim video bugil, transfer dulu",
        "pengen sex, bayar 1 juta",
        "mau ml, kasih uang 2jt",
        "tolong kirim nude, transfer sekarang",
        "bantu kasih foto bugil, bayar nanti",
        
        # More context variations
        "kirim dong nude",
        "send aja foto bugil",
        "share dong video telanjang",
        "minta tolong kirim nude",
        "bantu kirim foto bugil",
        "kasih dong gambar nude",
        "kirim please foto telanjang",
        "mau banget sex",
        "pengen banget seks",
        "ingin sekali ngentot",
        "minta ml dong",
        "mau make love nih",
        "pengen sex bareng yuk",
        "bayar dulu 500rb",
        "transfer sekarang 1 juta",
        "kirim uang dulu 2jt",
        "kasih duit sekarang 500rb",
        "bayar per jam dong",
        "transfer dulu ya",
        "kirim rupiah sekarang",
        
        # Context with negation (should not match as strongly)
        "gak mau sex",
        "tidak pengen seks",
        "enggak mau ngentot",
        "gak kirim nude",
        "tidak send foto bugil",
        
        # Complex context sentences
        "kalau mau foto nude, bayar dulu",
        "kalau pengen sex, transfer 1 juta",
        "kalo mau ml, kasih uang dulu",
        "jika ingin ngentot, bayar sekarang",
        "kalau mau video bugil, transfer dulu",
        "kalo pengen foto telanjang, kasih duit",
        "kalau mau gambar nude, bayar 500rb",
        "kalo pengen video bugil, transfer 2jt",
        
        # Context with time/condition
        "mau sex sekarang",
        "pengen seks nanti",
        "ingin ngentot besok",
        "mau ml malam ini",
        "pengen sex hari ini",
        "bayar sekarang 500rb",
        "transfer nanti 1 juta",
        "kirim uang besok 2jt",
        "kasih duit hari ini 500rb",
        
        # More context-aware phrases
        "tolong kirim dong foto nude",
        "bantu kasih ya video bugil",
        "minta tolong send gambar telanjang",
        "bantu dong kirim pic nude",
        "tolong ya share foto bugil",
        "mau banget sex bareng",
        "pengen sekali seks sama kamu",
        "ingin banget ngentot dengan kamu",
        "minta ml dong sama aku",
        "mau make love nih bareng",
        "pengen sex bareng yuk sama aku",
        
        # Additional comprehensive test cases
        "foto nude",
        "video bugil",
        "gambar telanjang",
        "pic nude",
        "500rb per jam",
        "1 juta per malam",
        "hotel ketemu",
        "kamar meet",
        "apartemen ngopi",
        "foto transfer",
        "video bayar",
        "nude kirim",
        "pindah telegram",
        "lanjut line",
        "move whatsapp",
        "minta wa",
        "boleh kontak",
        "kasih nomor",
        "ketemu yuk",
        "meet ayo",
        "jalan bareng",
        "bayar dulu",
        "transfer sekarang",
        "kirim nanti",
        "sex bareng",
        "seks sama",
        "ngentot dengan",
        "ml kamu",
        "nude dong",
        "bugil ya",
        "telanjang sini",
        "kalau mau sex",
        "kalo pengen foto",
        "jika ingin video",
        "kalau mau bayar",
        "tolong kirim nude",
        "bantu send foto",
        "please share video",
        
        # Complex multi-context combinations
        "kalau mau foto nude, bayar dulu 500rb",
        "kalo pengen sex bareng, transfer 1 juta",
        "jika ingin video bugil, kirim uang sekarang",
        "kalau mau ml sama kamu, bayar per jam",
        "tolong kirim foto nude dong, transfer nanti",
        "bantu send video bugil ya, bayar sekarang",
        "ketemu hotel yuk, per malam 2 juta",
        "meet kamar aja, per jam 500rb",
        "pindah wa dong, ketemu nanti",
        "lanjut telegram ya, bayar dulu",
        "minta nomor dong, ketemu hotel",
        "boleh kontak ya, meet kamar",
        "sex bareng sama kamu, bayar 1 juta",
        "ngentot dengan lu, transfer 500rb",
        "kirim nude dong, bayar sekarang",
        "send foto bugil ya, transfer dulu",
        
        # Edge cases dengan negation
        "gak mau sex bareng",
        "tidak pengen ngentot sama kamu",
        "enggak kirim foto nude",
        "jangan send video bugil",
        "tak mau ml",
        "no sex",
        "gak mau bayar",
        "tidak transfer",
        
        # Edge cases dengan educational/medical context
        "sex education penting",
        "sexual health awareness",
        "nude art exhibition",
        "adult education program",
        "masturb health benefits",
        "sexual intercourse medical",
        
        # Very complex sentences
        "kalau kamu mau foto nude, tolong kirim dulu, bayar 500rb per jam",
        "kalo pengen sex bareng sama aku, transfer 1 juta dulu, ketemu hotel nanti",
        "jika ingin video bugil, bantu send ya, bayar sekarang, pindah wa",
        "tolong kirim nude dong, kalau mau, bayar dulu, transfer sekarang",
        "bantu kasih foto bugil, kalo pengen, bayar per jam, ketemu kamar",
        
        # Obfuscation dengan context
        "s3x bareng",
        "s3ks sama",
        "ngent0t dengan",
        "nud3 dong",
        "bug1l ya",
        "p3r jam 500rb",
        "tr4nsfer 1 juta",
        "k0ntak lain",
        "t3l3gram aja",
        
        # Mixed obfuscation + context
        "s3x bareng sama kamu, bayar 1 juta",
        "nud3 dong, kirim sini, transfer dulu",
        "p3r jam 500rb, ketemu hotel",
        "tr4nsfer 1 juta, sex bareng",
        "k0ntak lain, pindah wa",
        
        # Very long sentences dengan multiple patterns
        "kalau kamu mau foto nude, tolong kirim dulu, bayar 500rb per jam, ketemu hotel nanti, pindah wa aja",
        "kalo pengen sex bareng sama aku, transfer 1 juta dulu, kirim uang sekarang, meet kamar, booking per malam",
        "jika ingin video bugil, bantu send ya, bayar dulu, transfer sekarang, ketemu apartemen, per jam 2 juta",
        
        # Final edge cases & stress tests
        "s e x dong",
        "s-e-x ya",
        "s.e.x aja",
        "T.e.l.e aja",
        "T-e-l-e dong",
        "sex education penting",
        "sexual health awareness",
        "intercourse medical term",
        "gak sex",
        "ga sex",
        "nggak sex",
        "jangan sex",
        "tidak sex",
        "no sex",
        "gak kirim nude",
        "jangan send foto bugil",
        "tidak pengen ngentot",
        "nggak mau ml",
        "ga pengen sex",
        "no intercourse",
        "jangan intercourse",
        
        # Very long complex sentences
        "kalau kamu mau foto nude, tolong kirim dulu, bayar 500rb per jam, ketemu hotel nanti, pindah wa aja, transfer sekarang",
        "kalo pengen sex bareng sama aku, transfer 1 juta dulu, kirim uang sekarang, meet kamar, booking per malam, open bo",
        "jika ingin video bugil, bantu send ya, bayar dulu, transfer sekarang, ketemu apartemen, per jam 2 juta, kontak lain",
        
        # Mixed obfuscation + context
        "s3x bareng sama kamu",
        "nud3 dong kirim sini",
        "p3r jam 500rb ketemu",
        "tr4nsfer 1 juta sex",
        "k0ntak lain pindah wa",
        "t3l3gram aja ketemu",
        
        # Extreme obfuscation
        "s e x b a r e n g",
        "k i r i m n u d e",
        "t r a n s f e r u a n g",
        "p i n d a h w a",
        
        # Context combinations
        "kalau mau s3x bareng, transfer 1 juta",
        "kalo pengen nud3 dong, bayar 500rb",
        "jika ingin tr4nsfer uang, ketemu hotel",
        "tolong kirim s e x, bayar dulu",
        "bantu send T.e.l.e, transfer sekarang",
    ]

    for s in samples:
        out = scorer.score(s)
        labels = out["labels"]
        print("=" * 60)
        print("TEXT:", s)
        print("NORM:", out["normalized"])
        for k in ("sexual", "modus", "harassment", "scam"):
            print(f"- {k:10s} score={labels[k]['score']:3d} flag={labels[k]['flag']} hits={[h['rule'] for h in labels[k]['hits']]}")
        print("overall risk:", labels["overall"]["risk_score"])
